### ISSUE TITLE
SettingWithCopyError from DataTable _update_columns

### ISSUE THREAD

**Issue by gsheni** [alteryx/woodwork#312]
### Bug Title

- There a pandas error being raised datatable._update_columns
- I cannot seem to produce this using the Woodwork demo dataset
- A [patch](https://github.com/alteryx/evalml/issues/1344#issuecomment-715598688) is to copy the dataframe during DataTable initialization. 

#### Code Sample, a copy-pastable example to reproduce your bug.

```python
import pandas as pd

pd.options.mode.chained_assignment = 'raise'

import evalml
from evalml import AutoMLSearch
X, y = evalml.demos.load_fraud(n_rows=100)
automl = AutoMLSearch(problem_type="binary", objective="auto", max_iterations=5)
X_train, X_holdout, y_train, y_holdout = evalml.preprocessing.split_data(X, y, test_size=.2)
automl.search(X_train, y_train)
```
### Stacktrace
```
             Number of Features
Boolean                       1
Categorical                   6
Numeric                       5

Number of training examples: 100
Targets
False    91.00%
True      9.00%
Name: fraud, dtype: object
`X` passed was not a DataTable. EvalML will try to convert the input as a Woodwork DataTable and types will be inferred. To control this behavior, please pass in a Woodwork DataTable instead.
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    automl.search(X_train, y_train)
  File "/Users/gaurav.sheni/evalml/evalml/automl/automl_search.py", line 390, in search
    X = ww.DataTable(X)
  File "/Users/gaurav.sheni/woodwork/woodwork/data_table.py", line 86, in __init__
    self._update_columns(self.columns)
  File "/Users/gaurav.sheni/woodwork/woodwork/data_table.py", line 220, in _update_columns
    self._dataframe[name] = column._series
  File "/Users/gaurav.sheni/evalml/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3040, in __setitem__
    self._set_item(key, value)
  File "/Users/gaurav.sheni/evalml/venv/lib/python3.8/site-packages/pandas/core/frame.py", line 3123, in _set_item
    self._check_setitem_copy()
  File "/Users/gaurav.sheni/evalml/venv/lib/python3.8/site-packages/pandas/core/generic.py", line 3681, in _check_setitem_copy
    raise com.SettingWithCopyError(t)
pandas.core.common.SettingWithCopyError:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
```

**Comment by tyler3991** [comment]
Closing. New accessor #483 will cover this.
